---
- name: Setup webserver using ansible
  hosts: webserver
  become: yes
  become_user: ec2-user

  tasks:
    - name: the same as sudo apt update
      apt:
        update_cache: yes
      when: ansible_pkg_mgr == 'apt'

    - name: the same as sudo install npm aand node
      apt:
        name: nodejs
        state: present
      when: ansible_pkg_mgr == 'apt'

    - name: the same as git clone
      git:
        repo: "https://github.com/alibekkenny/afisha_back_end.git"
        dest: "/home/ec2-user/afisha_back_end"
        version: main
        force: yes

    - name: the same as npm install
      npm:
        path: "/home/ec2-user/afisha_back_end"
        state: present

    - name: the same as npx prisma generate
      command: npx prisma generate
      args:
        chdir: "/home/ec2-user/afisha_back_end"

    - name: the same as npm start
      command: nohup npm start &
      args:
        chdir: "/home/ec2-user/afisha_back_end"

